version: '3.7'

services:
  db:
    container_name: $DB_CONTAINER
    restart: unless-stopped
    image: mariadb:latest
    volumes:
      - aka_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    networks:
      - lan

  akaunting:
    container_name: $AKAUNTING_CONTAINER
    restart: unless-stopped
    image: gslime/akaunting-alpine
    command: app:akaunting
    environment:
      - DEBUG=false
      - TZ=${TZ}

      - APP_LOCALE=${APP_LOCALE}

      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}

      - AKAUNTING_URL=${AKAUNTING_URL}
      - AKAUNTING_COMPANY_NAME=${AKAUNTING_COMPANY_NAME}
      - AKAUNTING_COMPANY_EMAIL=${AKAUNTING_COMPANY_EMAIL}
      - AKAUNTING_ADMIN_EMAIL=${AKAUNTING_ADMIN_EMAIL}
      - AKAUNTING_ADMIN_PASSWORD=${AKAUNTING_ADMIN_PASSWORD}
      - AKAUNTING_BACKUPS_EXPIRY=${AKAUNTING_BACKUPS_EXPIRY}
    depends_on:
      - db
    volumes:
      - sock:/sock
      - aka_data:/var/lib/akaunting
      - aka_www:/var/www/akaunting
    networks:
      - lan

  nginx:
    container_name: $NGINX_CONTAINER
    restart: unless-stopped
    image: nginx:1-alpine
    depends_on:
      - akaunting
    volumes:
      - sock:/sock
      - aka_www:/var/www/akaunting:ro
      - ./assets/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - ${VIRTUAL_PORT}:80
    networks:
      - lan
volumes:
  aka_db:
    name: $DB_VOL
  aka_data:
    name: $AKAUNTING_DATA_VOL
  aka_www:
    name: $AKAUNTING_WWW_VOL

networks:
  lan:
    name: $VIRTUAL_NETWORK
    driver: bridge
