version: '3.7'

services:
  db:
    container_name: $DB_CONTAINER
    restart: unless-stopped
    image: mariadb:latest
    volumes:
      - /srv/${VIRTUAL_HOST}/db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}

  # phpMyAdmin is optional
  pma:
    container_name: $PMA_CONTAINER
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - ${PMA_VIRTUAL_PORT}:80
    environment:
      PMA_HOST: $DB_CONTAINER
      MYSQL_ROOT_PASSWORD: $PMA_ROOT_PASSWORD

  akaunting:
    container_name: $AKAUNTING_CONTAINER
    restart: unless-stopped
    image: gslime/akaunting-alpine
    command: app:akaunting
    environment:
      - DEBUG=false
      - TZ=${TZ}

      - APP_LOCALE=${APP_LOCALE}

      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}

      - AKAUNTING_URL=${AKAUNTING_URL}
      - AKAUNTING_COMPANY_NAME=${AKAUNTING_COMPANY_NAME}
      - AKAUNTING_COMPANY_EMAIL=${AKAUNTING_COMPANY_EMAIL}
      - AKAUNTING_ADMIN_EMAIL=${AKAUNTING_ADMIN_EMAIL}
      - AKAUNTING_ADMIN_PASSWORD=${AKAUNTING_ADMIN_PASSWORD}
      - AKAUNTING_BACKUPS_EXPIRY=${AKAUNTING_BACKUPS_EXPIRY}
    depends_on:
      - db
    volumes:
      - /srv/${VIRTUAL_HOST}/sock:/sock
      - /srv/${VIRTUAL_HOST}/ak_data:/var/lib/akaunting
      - /srv/${VIRTUAL_HOST}/ak_www:/var/www/akaunting

  nginx:
    container_name: $NGINX_CONTAINER
    restart: unless-stopped
    image: nginx:1-alpine
    depends_on:
      - akaunting
    volumes:
      - /srv/${VIRTUAL_HOST}/sock:/sock
      - /srv/${VIRTUAL_HOST}/ak_www:/var/www/akaunting:ro
      - ./assets/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - ${VIRTUAL_PORT}:80
