#!/bin/bash
set -e

archive_name="Akaunting_${AKAUNTING_VERSION}-Stable.zip"
if [[ ! -f ${AKAUNTING_BUILD_DIR}/${archive_name} ]]; then
  echo "Downloading Akaunting ${AKAUNTING_VERSION}..."
  wget -q -O ${AKAUNTING_BUILD_DIR}/${archive_name} "https://github.com/akaunting/akaunting/releases/download/${AKAUNTING_VERSION}/${archive_name}"
fi

echo "Extracting Akaunting ${AKAUNTING_VERSION}..."
mkdir -p ${AKAUNTING_INSTALL_DIR}
cd ${AKAUNTING_INSTALL_DIR}
unzip -q -o ${AKAUNTING_BUILD_DIR}/${archive_name}
rm -rf ${AKAUNTING_BUILD_DIR}/${archive_name}

# set directory permissions
echo "Fixing directory permisions"
find ${AKAUNTING_INSTALL_DIR}/ -type f -print0 | xargs -0 chmod 0640
find ${AKAUNTING_INSTALL_DIR}/ -type d -print0 | xargs -0 chmod 0750
touch ${AKAUNTING_INSTALL_DIR}/.user.ini
chown -R ${AKAUNTING_USER}: ${AKAUNTING_INSTALL_DIR}
chmod 0660 ${AKAUNTING_INSTALL_DIR}/.env.example
chmod 0644 ${AKAUNTING_INSTALL_DIR}/.htaccess
chmod 0644 ${AKAUNTING_INSTALL_DIR}/.user.ini
