#!/usr/bin/env bash
set -e

source ${AKAUNTING_RUNTIME_DIR}/functions.sh

[[ $DEBUG == true ]] && set -x

case ${1} in
  app:akaunting|app:nginx|app:backup:create|app:backup:restore|artisan)

    case ${1} in
      app:akaunting)
        configure_akaunting
        echo "Starting Akaunting..."
        mkdir -p /run/php
        exec php-fpm -F
        ;;
      app:backup:create)
        shift 1
        backup_create
        ;;
      app:backup:restore)
        shift 1
        backup_restore $@
        ;;
      artisan)
        exec php $@
        ;;
    esac
    ;;
  app:help)
    echo "Available options:"
    echo " artisan              - Launch the artisan command"
    echo " app:akaunting        - Starts the Akaunting php-fpm server (default)"
    echo " app:backup:create    - Create a backup"
    echo " app:backup:restore   - Restore an existing backup"
    echo " app:help             - Displays the help"
    echo " [command]            - Execute the specified command, eg. bash."
    ;;
  *)
    exec "$@"
    ;;
esac
